---
title: "fiddler crabs"
author: "Marie Rivers"
date: "8/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(kableExtra)
```

```{r, echo = FALSE}
crabs <- read_csv(here("data", "HTL-MAR-FiddlerCrabBodySize.csv"))
```


```{r, fig.alt = "Scatterplot indicating positive correlation between latitude in degrees and crab carapace width in mm between Florida and Massachusetts.", echo = FALSE}
crab_plot <- ggplot(data = crabs, aes(x = Latitude, y = carapace_width)) +
  geom_point() +
  labs(title = "Crab size by latitude",
       x = "Latitude (degrees)",
       y = "Carapace width (mm)",
       caption = "Crab carapace width in mm compared to latitude in degrees")

crab_plot
```

```{r, echo=FALSE}
crab_table_data <- crabs %>% 
  group_by(Site) %>% 
  summarise(mean_width = round(mean(carapace_width), 2),
            sd_width = round(sd(carapace_width), 2),
            sample_size = n())

crab_table <- crab_table_data %>% 
  kable(col.names = c("Site Name", "Mean Width (mm)", "Standard Deviation of Width (mm)", "Sample Size"), align = "c") %>% 
  kable_paper() %>% 
  row_spec(c(1, 3, 5), background = "blue", color = "cyan") %>% 
  column_spec(c(1, 3), background = "darkgray", color = "red") 
  
  
crab_table
```

```{r, fig.alt = "Scatterplot showing crab carapace width (mm) decreasing as a function of mean annual water temperature (degrees Celsius).", echo = FALSE}
crab_scatter <- ggplot(data = crabs, aes(x = MATW, y = carapace_width)) +
  geom_point(aes(color = Site))

crab_scatter
```

Crab carapace width (mm) as a function of mean annual water temperature (degrees Celsius).

